# Generated by Django 5.1.6 on 2025-05-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_pro_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table=None,
        ),
    ]
